### ISSUE TITLE
@conda-forge-admin, please add user @ZzEeKkAa

### ISSUE THREAD

**Issue by ZzEeKkAa** [conda-forge/spirv-tools-feedstock#10]

**Comment by ZzEeKkAa** [comment]
@isuruf since https://github.com/conda-forge/spirv-headers-feedstock/pull/15 is merged it unlocks #9

**Comment by hmaarrfk** [comment]
please make the PR where you make the fixes, then in that PR ask to be made a maintainer.

Generally speaking, as a rule of thumb, it isn't always clear if the suggested fix will work. I'm more than OK with new maintainers (and here they would be greatly appreciated) but it is very difficult to judge the level of comfort somebody has with a particular recipe until they go through the motions.
